# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bdb512cd3da3dfb4c537efdcd6a64b1b4da42771bce9065a4f08fc506f64b8feed75a98ce85ac9ce28d4a30874528fa9542164c3004fcbb6511b8ece311143bf

test:
  secret_key_base: ad5ab98e7c8a5df1af8107956fa027c41ff207735051b11843ff60145b430a0ac0f2180b1866fca996c542fc7b2db641601e81724d3fa7daebfc08091ba89781

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
